# Homework-Week1

In [1]:
import numpy as np
import pandas as pd

### Question 1
What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

In [2]:
print(pd.__version__)

3.0.3

# Reading Dataset

In [11]:
df = pd.read_csv("../dataset_week1/car_fuel_efficiency.csv")

In [12]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

### Question 2
How many records are in the dataset?

In [21]:
df.shape[0]

9704

### Question 3
How many fuel types are presented in the dataset?

In [23]:
df.fuel_type.nunique()

2

In [24]:
data.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

### Question 4
How many columns in the dataset have missing values?

In [26]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [27]:
(df.isnull().sum() > 0).sum()

np.int64(4)

### Question 5
 What's the maximum fuel efficiency of cars from Asia in the dataset?

In [32]:
df.groupby("origin")["fuel_efficiency_mpg"].agg(["min", "max", "mean"])

             min        max       mean
origin
Asia    6.886245  23.759123  14.973830
Europe  6.200971  25.967222  14.942532
USA     6.695483  24.971452  15.040204

In [35]:
df[df.origin == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

### Question 6


1. Find the median value of `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?

In [36]:
df.horsepower.mean()

np.float64(149.65729212983547)

In [43]:
most_frequent_value = df.horsepower.mode()[0]
most_frequent_value

np.float64(152.0)

In [48]:
df["horsepower"] = df["horsepower"].fillna(most_frequent_value)
df["horsepower"]

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [49]:
df.horsepower.median()

np.float64(152.0)

### Question 7

1. Select all the cars from Europe
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

In [63]:
europe_cars = df[df["origin"] == "Europe"][["vehicle_weight","model_year"]]

In [66]:
europe_cars.head(7)

    vehicle_weight  model_year
0      3413.433759        2003
2      3079.038997        2018
4      3460.870990        2009
5      2484.883986        2008
10     3111.810181        2014
13     2274.735191        2000
16     2673.552941        2013

In [74]:
X = europe_cars.head(7).values

In [76]:
XTX = X.T.dot(X)

In [83]:
x_inv = np.linalg.inv(XTX)
x_inv

array([[ 7.99397664e-07, -1.16516410e-06],
       [-1.16516410e-06,  1.73367254e-06]])

In [84]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [88]:
w = x_inv.dot(X.T).dot(y)

In [89]:
w

array([-0.07188499,  0.63097065])

In [90]:
sum(w)

np.float64(0.559085655434893)